export enum UnitBisnis {
  BOSOWA_TAXI = 'BOSOWA_TAXI',
  OTORENTAL_NUSANTARA = 'OTORENTAL_NUSANTARA',
  OTO_GARAGE_INDONESIA = 'OTO_GARAGE_INDONESIA',
  MALLOMO = 'MALLOMO',
  LAGALIGO_LOGISTIK = 'LAGALIGO_LOGISTIK',
  PORT_MANAGEMENT = 'PORT_MANAGEMENT',
}
